import json
import os
from pathlib import Path
from datetime import datetime

# --- PATHS ---
LOGS = Path("/sdcard/Wormhole/MOTHER-BRAIN/logs/swarm_training.jsonl")
STORY_BIBLE = Path("/sdcard/Wormhole/ARCHIVE/Obsidian/NOMADZ_VAULT/Story_Bible/Timeline")
NOTION_STAGING = Path("/sdcard/Wormhole/MOTHER-BRAIN/00_inbox/TO_PROCESS/Notion_Sync")

def generate_narrative_branch(log_entry):
    """Turns raw RL rewards into a narrative event."""
    ts = log_entry.get("timestamp", "Unknown Time")
    reward = log_entry.get("reward", 0)
    
    # Narrative Logic: If reward is high, the swarm is 'evolving'
    event_type = "Evolutive Leap" if reward > 0.7 else "Standard Resonance"
    
    content = f"""# Narrative Branch: {ts}
## Event Type: {event_type}
**Data Context:** {log_entry.get('session')}
**Resonance Level:** {log_entry.get('coherence')}

### The Chronicle:
In the silence of the Crystalline Desert (Sector 7), the Fracture Team achieved a reward threshold of {reward}. 
The drones are no longer just navigating; they are beginning to 'see' the underlying lattice of the GEOLOGOS structure.

---
*Generated by OMEGA-CORE-01 v1.0*
"""
    return content

def run_scribe():
    STORY_BIBLE.mkdir(parents=True, exist_ok=True)
    NOTION_STAGING.mkdir(parents=True, exist_ok=True)
    
    if not LOGS.exists(): return
    
    with open(LOGS, "r") as f:
        for i, line in enumerate(f):
            data = json.loads(line)
            filename = f"Event_{data.get('session')}_{i}.md"
            
            # 1. Push to Obsidian
            with open(STORY_BIBLE / filename, "w") as out:
                out.write(generate_narrative_branch(data))
            
            # 2. Stage for Notion (via Vulture-Ingest)
            with open(NOTION_STAGING / filename, "w") as out:
                out.write(generate_narrative_branch(data))

    print(f"🖋️ [Vulture-Scribe] Narrative branches generated and pushed to Obsidian/Notion Staging.")

if __name__ == "__main__":
    run_scribe()
