using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Reflection;
using runnerDotNet;
namespace runnerDotNet
{
	public static partial class RunnerSettings
	{
		public static void Apply()
		{
			GlobalVars.runnerProjectSettings = new XVar(new XVar( "restAPIReturnEncodedBinary", true,
"restAPIAuthType", "basic",
"menuIds", new XVar( 0, "main" ),
"phpSpreadsheet", false,
"ext", "aspx",
"security", new XVar( "projectName", "",
"loginDataSource", "",
"loginForm", 3,
"dynamicPermissions", false,
"dpTablePrefix", "",
"dpTableConnId", "",
"providers", XVar.Array(),
"enabled", false,
"advancedSecurityAvailable", false,
"userGroupsAvailable", false,
"hardcodedLogin", false,
"defaultProviderCode", "",
"adOnlyLogin", false,
"sessionControl", new XVar( "lifeTime", 15,
"sessionName", "WB7s25OjU5TTWYkS7mqO",
"JWTSecret", "wIF7wUki17IwqoiMu5wE" ),
"registration", new XVar( "remindMethod", 0,
"hashAlgorithm", 0,
"passwordValidation", new XVar( "strong", false,
"minimumLength", 8,
"uniqueCharacters", 4,
"digitsAndSymbols", 2,
"upperAndLowerCase", false ),
"registerPage", false ),
"captchaSettings", new XVar( "captchaType", 0,
"siteKey", "",
"secretKey", "",
"passesCount", 5 ),
"emailSettings", new XVar( "fromEmail", "",
"usePHPDefinedSMTP", false,
"useBuiltInMailer", false,
"SMTPServer", "localhost",
"SMTPPort", 25,
"SMTPUser", "",
"SMTPPassword", "",
"securityProtocol", 0 ),
"advancedSecurity", new XVar( "allowGuestLogin", false ),
"auditAndLocking", new XVar( "loggingMode", 0,
"loggingTable", new XVar( "connId", "",
"table", "" ),
"loggingFile", "audit.log",
"logSecurityActions", false,
"lockAfterUnsuccessfulLogin", false,
"enableLocking", false,
"lockingTable", new XVar( "connId", "",
"table", "" ),
"tables", new XVar(  ) ),
"twoFactorSettings", new XVar( "available", false,
"required", false,
"enable", true,
"remember", true,
"types", new XVar(  ),
"twoFactorField", "",
"emailField", "",
"phoneField", "",
"codeField", "",
"projectName", "" ),
"staticPermissions", new XVar( "groups", new XVar(  ) ),
"adAdminGroups", XVar.Array(),
"showUserSource", false,
"dbProviderCodes", XVar.Array() ),
"notifications", new XVar( "enabled", false,
"table", new XVar( "connId", "",
"table", "" ) ),
"allTables", new XVar(  ),
"tablesByShort", new XVar(  ),
"tablesByGood", new XVar(  ),
"events", XVar.Array(),
"languages", new XVar( 0, new XVar( "name", "English",
"nativeName", "English",
"rtl", false,
"filename", "English.lng" ) ),
"languageNames", new XVar( 0, "English" ),
"defaultLanguage", "English",
"detectDefaultLanguage", true,
"charset", "utf-8",
"codepage", 65001,
"defaultConnID", "conn",
"wrConnectionID", "",
"wizardBuild", "43785",
"projectBuild", "WX7qRxEPAdiI",
"projectTheme", "default",
"projectSize", "normal",
"customErrorMsg", new XVar( "text", "Error occured.",
"type", 0 ),
"cloudSettings", new XVar( "cloudAmazonRegion", "",
"cloudAmazonBucket", "",
"cloudAmazonAccessKey", "",
"cloudAmazonSecretKey", "",
"cloudWasabiRegion", "",
"cloudWasabiBucket", "",
"cloudWasabiAccessKey", "",
"cloudWasabiSecretKey", "",
"cloudGDriveClientId", "",
"cloudGDriveClientSecret", "",
"cloudOneDriveClientId", "",
"cloudOneDriveClientSecret", "",
"cloudOneDriveDrive", "",
"cloudOneDriveAccountType", 0,
"cloudOneDriveDirectoryId", "",
"cloudDropboxClientId", "",
"cloudDropboxClientSecret", "" ),
"mapSettings", new XVar( "embed", true,
"provider", 0,
"apikey", "" ),
"viewPluginsWithJS", XVar.Array(),
"rtlLanguages", new XVar( "English", false ),
"smsSettings", new XVar( "smsProvider", 4,
"iBusername", "",
"iBpassword", "",
"iBsender", "",
"essUsername", "",
"essPassword", "",
"essSender", "",
"gwApiToken", "",
"gwSender", "",
"mbAuth", "",
"mbSender", "",
"twilioSID", "",
"twilioAuth", "",
"twilioNumber", "",
"phoneField", "",
"counryCode", "+1",
"wauUsername", "",
"wauPassword", "",
"wauSender", "" ) ));
		}
	}

}
